### ISSUE TITLE
delete my account

### ISSUE THREAD

**Issue by kidalikevin** [NativeScript/playground-feedback#119]
I want you guys to delete my account kidalikevin, nativescript sucks.

**Comment by darind** [comment]
@kidalikevin, sorry to hear your disappointment with NativeScript. In order to delete your account, plase log into your account and use the [Privacy Management](https://app.onetrust.com/app/#/webform/7897e80a-b8a4-4797-883a-bdacfe1ab8e4) link to submit a formal request.

![image](https://user-images.githubusercontent.com/270695/50758113-e6873f00-1269-11e9-8bba-15ae9d037ce2.png)
