### ISSUE TITLE
RadSideDrawer 4.0.0 not opening on playground.

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/playground-feedback#26]
here is playground link [https://play.nativescript.org/?template=play-ng&id=IGa87M](https://play.nativescript.org/?template=play-ng&id=IGa87M)

i'm also attaching the local project zip file
[drawer.zip](https://github.com/NativeScript/playground-feedback/files/1946987/drawer.zip)

both are identical but on playground it is not working as expected.
we can't open drawer from component and also when drawer is opened by swiping it doesn't show over navigation  bar.

i had implemented sidedrawer as a root element in app.component.html

**Comment by NickIliev** [comment]
@bhavincb thank you for reporting this issue. The PlayGround is wrapping the test code in the Preview application which is causing the difference in the behavior. We will investigate the possibilities to improve the sidedrawer behavior at the root level.

However, you should not worry because the exported code will work exactly as expected on real device and emulators.

**Comment by bhavincb** [comment]
hii @NickIliev ,

yes downloaded code works fine in local environment. but people checking new feature from documentation on play ground might be confused and may think that this feature is broken.

**Comment by darind** [comment]
@bhavincb, thanks for submitting this issue.

After further investigation it turns out that it is related to the `nativescript-angular@5.2.0` module used in the Playground. This issue is resolved in `nativescript-angular@5.3.0`.

I will let you know once we update the Preview app.

**Comment by darind** [comment]
@bhavincb, we have published a new version of the Preview app which should resolve the issue with the sidedrawer component.
