### ISSUE TITLE
If one app has an error in Preview, you can't load another app in Preview

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/playground-feedback#31]
I ran into an error that I'm still working through on [this app in the Playground](https://play.nativescript.org/?template=play-tsc&id=T90rxQ&v=5). This causes Preview to error out, understandably. However, if I switch to work on a new app in the Playground and scan a new QR code, the Preview app is stuck on the app with the error.

By scanning a new QR code, the Preview app does not reload a new app. Instead, the old app remains loaded in Preview in its errored state, even after killing the app on my device. My "fix" is to resolve the error on the old app, but it would be nice if Preview could just load a new app, regardless of the state of the current one.

**Comment by rdlauer** [comment]
Yes I can still replicate it (this is on iOS...on Android I can't even get the first app to load in Preview, just leaves a white screen):

1. Kill the Playground/Preview apps on my device.
2. Open up this [Playground project](https://play.nativescript.org/?template=play-tsc&id=T90rxQ&v=5) and scan the code.
3. It throws an error.
4. Open up a new Playground project [like this one](https://play.nativescript.org/?template=play-tsc&id=Y4fVGt&v=2) (I don't think it matters).
5. Kill the Playground/Preview apps again, just for fun.
6. Scan the QR code again. The preview app doesn't update from the old error.

**Comment by rdlauer** [comment]
What's interesting is I went back to this 30 mins later, loaded up a different project, and the app loaded up just fine. Now I'm confused :)

**Comment by vhristov5555** [comment]
It isn't a good idea to kill the app when there is an error in iOS. We have added the screen to prevent people of closing the preview app:
![image](https://user-images.githubusercontent.com/7846198/40005555-e0d4f0fe-57a0-11e8-8cd3-1d8dd3fe7c76.png)

We are aware of this limitation. But in our point of view there isn't much difference if you scan a new QR or just open the preview app to see the reason for the crash of the app.
The second part of the problem is that there are two types of behavior when there is an error:
-	If the app crash. You can use this saved session https://play.nativescript.org/?template=play-js&id=3p3qsa:
o	The app will be closed
o	Open the app to see the error
o	Close the preview app
o	Scan new QR(https://play.nativescript.org/)
o	The app will open again and the new project will be loaded (This is more a side effect than a feature)
-	If the error screen is shown without a crash. You can use this saved session https://play.nativescript.org/?template=play-js&id=ccxy6M:
o	Close the preview app
o	Scan new QR(https://play.nativescript.org/)
o	The old error will be shown and the new project won’t be shown

**Comment by rdlauer** [comment]
Ok, that makes sense. So just to be clear (and for anyone else experiencing this issue in the future), you should really clear up any existing errors on your current Playground project before you try and scan a new project in? Is that accurate?

**Comment by vhristov5555** [comment]
No if you don't close the preview app and scan a new QR code the new project should be loaded correctly. The problem appears only when you kill the preview app on the Error screen.

**Comment by rdlauer** [comment]
Perfect, thanks!

**Comment by Coyote6** [comment]
May I suggest adding a reset button to the home screen of the playground app, that takes you to this qr code automatically, and gives the instructions to rescan your QR after it errors.  I struggled for a while with this until I finally found this post.  Thanks.

**Comment by danbord** [comment]
Stuck here too.  My Iphone cannot load the application anymore even if I fixed the issue.  My iPad works fine with the same code
