### ISSUE TITLE
Wrong cursor position in Web Playground IDE

### ISSUE THREAD

**Issue by traBolic** [NativeScript/playground-feedback#32]
Hi

I don't know if this is the right place but I'm gonna write this issue anyway..

So, I've been started yesterday learning how things goin on in NativeScript and trying things in web based IDE. But this little cursor position issue is making me crazy af.
http://prntscr.com/jhtwf6

If you can do something about this, I would be much grateful to you. Thank you!

**Comment by vhristov5555** [comment]
Sorry for the inconvenience caused.

We are using Monaco editor. We were able to reproduce the same behavior in their playground(https://microsoft.github.io/monaco-editor/playground.html)

The problem is that when you have marked part of the text and you try to click inside the marked text the cursor is not going to be moved from the previous position. If you click outside the marked part of the text the cursor will be moved. 

If this behavior is changed by the Monaco editor in feature we will let you know.
