### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by Denisijcu** [NativeScript/playground-feedback#46]
Please,,, I need to know how to deploy my proyect. I finished in the playground but I can't run it in Nativescript Sidekit..      My proyect run 100% fine here.  

https://play.nativescript.org/?template=play-ng&id=ZTbu19&v=11

I appreciate your help , thanks

**Comment by darind** [comment]
Your specific playground session contains some third party plugins which cannot be built with SideKick cloud build due to some missing typing definitions. In order to make a cloud build you may need to replace those plugins with global `npm` packages using `npm add nativescript-xxxxx --save` and then replace the corresponding references in your code.
