### ISSUE TITLE
Failed to find module: "nativescript-lan-scan"

### ISSUE THREAD

**Issue by VladimirDVV** [NativeScript/playground-feedback#77]
After adding the plugin nativescript-lan-scan(using npm package feature available on playground) I get the error Failed to find module: "nativescript-lan-scan"
Below is the link to the application:
https://play.nativescript.org/?template=play-ng&id=okPIyZ
 browser:Chrome
 platform:Android

**Comment by vtrifonov** [comment]
Adding an npm package to the playground adds the content of the package inside the application and in order to use it you need to use the relative path like `"../nativescript-lan-scan"`. However you cannot use this plugin as it contains a [pod file](https://github.com/burkeholland/nativescript-lan-scan/tree/master/platforms/ios) and this is one of the limitations of the playground:
**_Note: Adding {N} plugins that depend on CocoaPods or Android libraries or require changes to the App_Resources is not currently supported and might not work as expected._**
