### ISSUE TITLE
Playground UX

### ISSUE THREAD

**Issue by vedranstanic82** [NativeScript/playground-feedback#97]
Hi all,

Just a quick suggestion to make the Playground more attractive for newcomers. Currently in order to quickly share a snippet of code and/or a log message it is more attractive to use Pastebin. It allows for an anonymous quick paste and share url. I was advised to use the Playground instead, but it was a bit of a process: create a Telerik account (ok, but when i tried with Google Login i was redirected to a json page with an error message). Once i created a manual login with my company email address I was able to play with the code editor, and yes I could paste the code/error/anything log in there, but I didn't see an easy way to share the code via a URL. Found this: https://www.nativescript.org/blog/life-is-easier-with-nativescript-playground and I can see a Share button up top, but I don't have one in my browser. Now it may be that i can just copy paste the URL of the project, but then I am not sure whether the other person needs to have a telerik account to see it or not, and will it even open up the same project?

Just some first time User Experience feedback on code sharing. I hope you find it helpful.

Thanks,

Vedran

**Comment by vtrifonov** [comment]
Hi @vedranstanic82, аactually you don't need to log in in order to share a project, but if you are logged in and save a project you will be able to get the list of your projects otherwise you will need to save somewhere the project url in order to be able to find it again later. As for the "Share" button we have renamed it to "Save" now. So just writing the code and pressing the Save button will give you a popup with "Copy Url" button or you can copy the url from the browser and share it with someone else. There is no need either for you nor for the other person to log in however.

**Comment by vedranstanic82** [comment]
Thanks and understood @vtrifonov - my feedback is that for the first timers all of this is a bit unknown until someone clicks around and tries it out (sharing, saving, etc.)
